export const ACTION_TYPE = {
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	LOGOUT: 'LOGOUT',
	RESET_POST_DATA: 'RESET_POST_DATA',
	SET_POST_DATA: 'SET_POST_DATA',
	SET_USER: 'SET_USER',
};
